# Generated by Django 5.1.2 on 2024-11-07 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comuna', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCampana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_campana', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_transaccion', models.IntegerField()),
                ('fecha_donacion', models.DateField()),
                ('referencia_webpay', models.CharField(max_length=100)),
                ('estado_transaccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campana', models.CharField(max_length=200)),
                ('descripcion_campana', models.TextField()),
                ('monto_objetivo_campana', models.IntegerField()),
                ('fecha_fin_campana', models.DateField()),
                ('fecha_inicio_campana', models.DateField()),
                ('link_webpay', models.URLField(max_length=500)),
                ('imagen_campana', models.ImageField(blank=True, null=True, upload_to='imagenes_campana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipocampana')),
            ],
        ),
        migrations.CreateModel(
            name='Donador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_pat_donador', models.CharField(max_length=100)),
                ('apellido_mat_donador', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_registro_donador', models.DateField()),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_publicidad', models.CharField(max_length=100)),
                ('descripcion_publicidad', models.TextField()),
                ('precio_publicidad', models.IntegerField()),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campana')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campana')),
                ('donador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.donador')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transaccion')),
            ],
        ),
    ]
