# Generated by Django 5.1.2 on 2024-11-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_donacion_donador_donacion_fecha_donacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='monto_donado',
            field=models.IntegerField(default=0),
        ),
    ]
