# Generated by Django 5.1.2 on 2024-11-09 02:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_campana_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
